In [3]:
import numpy as np

In [4]:
np.linspace(0, 2, 15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [7]:
my_3d_array = np.array([
    [[1.1, 2.1, 3.1], [4.1, 5.1, 6.1]],
    [[7.1, 8.1, 9.1], [10.1, 11.1, 12.1]]
])
my_3d_array.shape

(2, 2, 3)

In [8]:
print(type(my_3d_array))
print(my_3d_array.dtype)
print(my_3d_array.shape)
print(my_3d_array.size)
print(my_3d_array.ndim)

<class 'numpy.ndarray'>
float64
(2, 2, 3)
12
3


In [9]:
#convert to 4D
my_4d_array = np.array(my_3d_array, ndmin=4)
print(my_4d_array.ndim)
print(my_4d_array.shape)

4
(1, 2, 2, 3)


In [10]:
#convert to integer
my_new_array = my_4d_array.astype(int)
print(my_new_array)
my_new_array.dtype

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


dtype('int64')

In [12]:
#print all num
for x in np.nditer(my_new_array):
    print(x, end= ' ')

1 2 3 4 5 6 7 8 9 10 11 12 

In [13]:
#print num 8
print(my_new_array[0, 1, 0, 1])

8


In [14]:
#print num 5 and 6
print(my_new_array[0, 0, 1, 1:])

[5 6]


In [15]:
#find num 8
print(np.where(my_new_array == 8))

(array([0]), array([1]), array([0]), array([1]))


In [16]:
my_new_array.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [17]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

joined_arrays = np.concatenate((arr1, arr2))
print(joined_arrays)

[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


In [18]:
joined_arrays2 = np.concatenate((arr1, arr2), axis = 1)
print(joined_arrays2)

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


In [19]:
split_joined_arrays = np.array_split(joined_arrays, 2, axis = 1)
print(split_joined_arrays)

[array([['A'],
       ['E'],
       ['C'],
       ['G']], dtype='<U1'), array([['B'],
       ['F'],
       ['D'],
       ['H']], dtype='<U1')]
